### ISSUE TITLE
jupyter notebooks kernel runs correctly

### ISSUE THREAD

**Issue by accon** [OpenEnergyPlatform/examples#82]
After installation with the requirements.yml file for the API and manually installing jupyter notebook in the environment I ran the first tutorial notebook but its kernel fails as shown below. 

Traceback (most recent call last):
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\jupyter_client\connect.py", line 100, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\wulf_ni\.conda\envs\oep-api\lib\site-packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
    import win32api
ImportError: No module named 'win32api'

**Comment by accon** [comment]
I'm using the following specs on a Windows10 OS.
     conda version : 4.6.14
     python version : 3.7.3.final.0
     user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17763

**Comment by Ludee** [comment]
Hi @accon, 
I could not reproduce this error. Is it still not working or do you need help?
